spring:
  redis:
    host: localhost
    port: 6379
    client-type: lettuce

  datasource:
    url: jdbc:mysql://localhost:3306
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hatsune39